<?php
return array(
	// CSS Files
	'common' => array(
		'//templates/otnewz/assets/styles/normalize.css',
		'//templates/otnewz/assets/styles/OTnewzBase.css',
	),
	'links' => '//templates/otnewz/assets/styles/OTnewzLinks.css',
	'forms' => '//templates/otnewz/assets/styles/OTnewzForms.css',
	'members' => '//templates/otnewz/assets/styles/OTnewzMembers.css',
	'profile' => '//templates/otnewz/assets/styles/OTnewzProfile.css',
	'groups' => '//templates/otnewz/assets/styles/OTnewzGroups.css',
	'live' => '//templates/otnewz/assets/styles/OTnewzLive.css',
	'rss' => '//templates/otnewz/assets/styles/OTnewzRSS.css',
	'pages' => '//templates/otnewz/assets/styles/OTnewzPages.css',
	'misc' => '//templates/otnewz/assets/styles/OTnewzMisc.css',
	'OTslider' => '//templates/otnewz/assets/styles/OTnewzOTslider.css',
	'modules' => '//templates/otnewz/assets/styles/OTnewzModules.css',
	'sidebar' => '//templates/otnewz/assets/styles/OTnewzSidebar.css',
	'footer' => '//templates/otnewz/assets/styles/OTnewzFooter.css',
	'custom' => '//templates/otnewz/assets/styles/OTnewzCustom.css',
	'helper' => '//templates/otnewz/assets/styles/helper.css',
	'print' => '//templates/otnewz/assets/styles/print.css',
	'themeDefault' => '//templates/otnewz/assets/styles/OTnewzThemeDefault.css',
	'themeAzure' => '//templates/otnewz/assets/styles/OTnewzThemeAzure.css',
	'themeBlue' => '//templates/otnewz/assets/styles/OTnewzThemeBlue.css',
	'themeCyan' => '//templates/otnewz/assets/styles/OTnewzThemeCyan.css',
	'themeDark' => '//templates/otnewz/assets/styles/OTnewzThemeDark.css',
	'themeGray' => '//templates/otnewz/assets/styles/OTnewzThemeGray.css',
	'themeGreen' => '//templates/otnewz/assets/styles/OTnewzThemeGreen.css',
	'themeMaroon' => '//templates/otnewz/assets/styles/OTnewzThemeMaroon.css',
	'themeOrange' => '//templates/otnewz/assets/styles/OTnewzThemeOrange.css',
	'themePink' => '//templates/otnewz/assets/styles/OTnewzThemePink.css',
	'themeRed' => '//templates/otnewz/assets/styles/OTnewzThemeRed.css',
	'themeSilver' => '//templates/otnewz/assets/styles/OTnewzThemeSilver.css',
	'themeTeal' => '//templates/otnewz/assets/styles/OTnewzThemeTeal.css',
	'themeViolet' => '//templates/otnewz/assets/styles/OTnewzThemeViolet.css',
	'themeYellow' => '//templates/otnewz/assets/styles/OTnewzThemeYellow.css',
	// JavaScript Files
	'commonJS' => array(
		'//templates/otnewz/assets/scripts/jQuery.bPopup.js',
		'//templates/otnewz/assets/scripts/jQuery.hoverIntent.js',
		'//templates/otnewz/assets/scripts/jQuery.Superfish.js',
		'//templates/otnewz/assets/scripts/jQuery.EasyTabs.js',
		'//templates/otnewz/assets/scripts/jQuery.Dropdown.js',
		'//templates/otnewz/assets/scripts/mediaMatch.js',
		'//templates/otnewz/assets/scripts/enquire.js',
	),
	'embedJS' => array(
		'//templates/otnewz/assets/scripts/jQuery.imagesLoaded.js',
		'//templates/otnewz/assets/scripts/jQuery.Embedly.js',
		'//templates/otnewz/assets/scripts/OTnewzEmbed.js',
	),
	'OTsliderJS' => '//templates/otnewz/assets/scripts/jQuery.ResponsiveSlides.js'
);